# Generated by Django 3.2.5 on 2021-07-25 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockmgmt', '0008_rename_timestamp_stockhistory_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockhistory',
            old_name='time',
            new_name='timestamp',
        ),
    ]
